name: clang-format Check

on:
  push:
    branches:
      - master
    paths:
      - '**.hpp'
      - '**.cpp'
      - '**.h.in'
      - '**.c'
  pull_request:
    paths:
      - '**.hpp'
      - '**.cpp'
      - '**.h.in'
      - '**.c'

permissions:
  contents: read

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - 'config'
          - 'examples'
          - 'include'
          - 'src'
          - 'test/include'
          - 'test/src'
    steps:
    - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
    - name: Run clang-format style check for C/C++ programs.
      uses: jidicula/clang-format-action@c74383674bf5f7c69f60ce562019c1c94bc1421a # v4.13.0
      with:
        clang-format-version: '10'
        check-path: ${{ matrix.path }}
        include-regex: '^.*\.(hpp|cpp|h\.in|c)$'
        fallback-style: 'Google'
