name: clang-format Check

on:
  push:
    branches:
      - master
    paths:
      - '**.hpp'
      - '**.cpp'
      - '**.h.in'
      - '**.c'
  pull_request:
    paths:
      - '**.hpp'
      - '**.cpp'
      - '**.h.in'
      - '**.c'

permissions:
  contents: read

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - 'config'
          - 'examples'
          - 'include'
          - 'src'
          - 'test/include'
          - 'test/src'
    steps:
    - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
    - name: Run clang-format style check for C/C++ programs.
      uses: jidicula/clang-format-action@f62da5e3d3a2d88ff364771d9d938773a618ab5e # v4.11.0
      with:
        clang-format-version: '10'
        check-path: ${{ matrix.path }}
        include-regex: '^.*\.(hpp|cpp|h\.in|c)$'
        fallback-style: 'Google'
